{% set name = "jupyter_dojo" %}
{% set version = "0.3.2" %}
{% set sha256 = "a473ba827fcbf8f99c86373c7863b95e308ecc9c9efafe1ddd4180310efcaa8e" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record record.txt
    - jupyter nbextension install jupyter_dojo --py --sys-prefix --overwrite

requirements:
  build:
    - python
    - ipython_unittest >=0.3
    - notebook >=4.3
    - jupyter

  run:
    - python
    - notebook >=4.3
    - jupyter
    - ipython_unittest

test:
  imports:
    - jupyter_dojo

about:
  home: https://github.com/JoaoFelipe/ipython-unittest
  license: MIT
  license_family: MIT
  summary: 'Install the coding dojo extension for ipython_unittest'
  dev_url: https://github.com/JoaoFelipe/ipython-unittest

extra:
  recipe-maintainers:
    - JoaoFelipe
