# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rnANwVBkX3D/GoOF9wl7K/lIj8tnPJlF3vOvl+gBYHjVQNx88AwxVg9yFmglXtiQhUaKufkZogX8/50ybimbYhyqgNOuA3xtC7sGu9lrrrHUyfJMQelGX+0V95Go9DeLDNoAd5YDtYjboEgV6l8FgSQkxIWcTP1w59GLDky8KTq8gXiQSmba/CCDu+Qkrxa/gh4KxbkPq3JBm09ifZ04+2yQOe5EdYREGlBSOa1mccBkjQIg/Mu6faE4cJ53/BzvLmXyM8n74muwjuWGAqUiU7QmVlWUTxgcl+F5nRNRYVhZa1mykmTq4cyAzVhwv0lAtTNmG6iNsuEeg2mV3QYBJ6cwLhUIasMypTGnBS1wBO0XuGZb75TQdvaO30rhmiiTvpMyGv8q3iAGX5pwPFURzxwY5i16BYW+ZV8H2+pmRYUBBwfcJvJhq33RAj3AZeu7jU3tCBGUlZGnGt8UHyPrCUEIU613k97vtJphJLJGDnXyREW+IV8UQIrBwMaWLH2nxReVgchgTxi313uF+caCwN4OPO0LLgLGkz4PrVS2YtmBuaREK3V7EGy2Tuyf1wBmy+prh3uVSMThQG6Dubsn5+Q/Yi20aAshk1aAsj7ZyYvNamzwZcg3C9dXomDGMh2n4buu2PP1JIYqgohao/5aURx5xa+whipR5QX/XRXje3o="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
