# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "yP7OWhNRaip05Se4HZQWdiOjyTT35zZyczutTvkZZ4Q/5XBNPq4PR+BwCPy2VtTwvS6B1ykyoFb0hOLBS/AOG6k9x4SAuLvxgFTWDWi28A5+vV6EdJf3ERbqampeVT2lfZhXSfTt+Rtmz4WAfGDMUZOHz3Cz2WTv+NTlgxbwXQ4JuyLxmBvI0tPiYX0RDAeJ7GXQQdNFG9mCVe1jWD9fcGrVmbbBsBhMtdc+bzfNclMQ/6U54hGyMkiIYKsA/5H/CZRvnTtgV5/C6uVNs5aPT7rgtOqm3C6lE4Lh8rEGqABx76XrzaOTBBrXxtemZiO738QA4XVTNJ6r2EDp6ArYups4IYzpRhb1bLZdOQEU6B+BEmhi5q2kqg3+8GxeZ/gQmmlKiNp4MT1qaf6iHDXjyJPtOZjHTJVJ5MM+M5LTOEpTkw5W2lvdP+2jJt3HCHWFY5BTyP7ylLuhtXZ0olp4r0E1aUpicJKBYFgPf9kR4pWbJp2ts42M4X9IYHvXftAK8RQ+mpJFAexhs1X7SOD76pBYT9yVD+5e13liUEXg9EteKWVV9b1mvJRu7TsTcZ4uhArgfgVWe8dzbMf9UG5+QdrYwd+SXlKo2yFw1wjiaoTZRgFUaxl9h3M0288uA8TzDd045I1PaD+0++LFkaNvM3jgKjh+08FFPeyYw5rPH/c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
