travis:
  secure:
    BINSTAR_TOKEN: xg6HXJD+8p3uuDL+abUOoR/y/KebGhTM1Tdslqy0EG3T3vRG3vgTWsHwaE6D5vG82Y8U2J4Vg0KZp3XjdP03cPwKVztGsPhyRecpZU3xDehs7PekYgEdYZcrNrb9LD2jqXf0GGK5k/AYHh7QslJuB8i3JKPNdnXnCAURPchWTWoA2RgQf+8OwXVJROt7oDf9gYlHWfHM7cLE5hUVkAr0At60u5w4S/hAaIlOTCL2R5ZzFHDDwgOqiTbUplFZUeM4LEHt4MSUtU531jMPXzNPr48CDz8R9OvRuFe2f5DpjM4PrC6oUhI/e0udm4e9rjH1hTkqZADOGjB5JBYWOsOMKbUy3zIwUmbvMhTavmoPCdI2ZmxuUTCN2rdAQ6Lxw/+JpYgKtukQ/sKks1gSRJwubfi7S2tEuwYIiS/iZu2I6itkLyzfkYfKWhT4JaaRnvHNqCB3e3phmeD1r1CQYt8XZgjPfQQGO4z4Wu8kxW3xaZ/Gk2xHwP4umlT9QoYFZwpPQKfnC6D8uhQ5ZKJV69NWyDi/GRLdfo8B5WWVtE6o4P1MRhuKo8uameHDLzNIcgi4TEFCxQhZOZDfzIJCyqxU34ctw98TzW0DvX0c+sdM3p6DgItef4MZlXi4I+o02voGluKQv7QJHpznn7kdyCmkuUF5IlDT8fZMb2XiqQ1b6Uo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
