travis:
  secure:
    BINSTAR_TOKEN: axwpXOqQzN15kirgML5FiTKg3aj7xQU2uS6skD5NqdgS8OrdFuWiD0DjbI6Gnd7sivKtbRlEO4TSGE+2NeecJEBvbiMJ84RVnicXgWPsyYUC+LJr5E6JivmPsEc5M4bnXtU53jTU87DRwuSb5hCcaQKTqOyI6GUwn2VeDhxFsJuhgyLwgP1qvQxNAJq06PqSctYzcuMAanFCEOKtsvVKBrQfOTJWujp48VQCByouZO6edh2WCxWKxapqc/4rYHDmiKJ1B66czZvbQ5aPmA+ouyudTKMDu9HsRgkrAM09SAeiZ0dq1YfIBz8F9swA5d1/Rih1YoOgSGB0m0DqEZ7aVcjns7Lzgy4FCzNszK1AG4PS62YMUg8h7f+puNGBx98zBBlVIkU10KX1WMyfWIIjPJ/p2SAtzxJM4IMg976HPsmcMkLxGF3OytY0eJB5zIcVnXu09hzMRfW4YUgVha3LIlbO6aB+e8DZDdQe/0Dc/0zSOfERmZ7qQLQQMQfN1g4PC698bTjn9xbnkwW9CJ22DzLI3d91v5qkk5jgfPIiFOaqBSlekW6vKhVvHlSqxJ6MNIz7yTBfnO0IHNaM6RmHfiopwY+v2bqpC2HfSOQTZeVaSSB+VREKywuVfkDQTgMzpwubnS/ypAUL8ggY2AtMJ5fwEg22yP66dUH1cyaL20E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
