travis:
  secure:
    BINSTAR_TOKEN: t+exwjxZt5hHX0Wi6H216lfYqVGc1nMGoiyCQB8TsC0arUzY2SQBKbjIK51uizKRqTALp074iBzbcvTUY9/Dxpa2yt/LNCmVkMNEmUKeh2mhN6ITHHwiIRO1vnSN5M2+lAQyYCEMRqA89pfF01DGTjRDjN/L5XUf4vMKvXk9h3UnO/erVS4BVWkUL3JjDepyK//o5X2cX7j4nDkH2LzBaB8aHApOgNiKt2lSpDC2iOsqjcbXd7Vt4W+KPmTqHRv9MDPYUzrUpLUmtXXthoK9R4MDeTdw0QiITBDYNDUmlVCSHTip4G7ORpdfWv51XE7Znmt9OYu1tTgB/L76G0pcYjuDfKKwgVtx4pmJ8N2GJhthxoQv0bJ1h1VgtGtQLdSXyH4ZC7DNcxar2HoUsYhPXCS/j+eEGN6hmeuH4aQy7dMr36rr9o8CqRC0urbCNa0OBWvbni5lqpIMwEeaqe1rdUvD1Uf79k3sQ6nVEXPn6VswY2G1Zos2sLXhAYEBfwYu9VxfD2imHHYfye/HYeWG8m45sPxFnGY8AxyNrqJMdNVpVvOuwu1xzz8sxbdoohMOsmqSrMNTT96u+iKkjoGHXsfFNU8U+PIsPAgN7F8qJbffnzoEcbYSPrnky0anWoU29SLzHFF4qA8vBHgJdDjigg5Rg13ZTT3Vy/ee1AyWxWQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
