travis:
  secure:
    BINSTAR_TOKEN: tCR+iUX8gxmoBkWTVx4ehWZOa484OGs3XciciSJ26x235U0EO1le8pqIX26RD2wj/naq1MqFS44LDUZt2rAQVUSSrQsZE3SY/uH7fw8Ybe31i1cFA8tzq22FcBp1kiUvVeHvTBYacgAYmJIQQ0ChgZQvZngwoJxZNEU02GQoMgu4kmWoFTIGlKs06psUfbacq64WhH1Iakp3xR6xBTbDKuPG4TyGtNqai5kLcxke9gH9D0YvZa88K/D9pflCjjmEuYeTPYHQr3rblYQDlWjLwzlglEQ58k2YUwCBZLr1gkHKHY4ZpkqQpzTfDFIsBGe8c6PJiPXPz7uKTZun3B+JSwQOl7/jmRyyl+W0PRWlsE+AKPEsAmZp33gYRXUnjEmvV3pyPICIHG98Pe6zTu7+DcPumtSikv9eOueqsAE0JQrF6o6qQbZQJl5YGY1F6cmLoR0ymhaDoi3KQSossYc9e/SDnQmwk9VWBeX9DCpZuo3HH4Hmnjk7rebblRtpRME1MkT3Cmh/bvl6LfH4kb+15BGNH+vXAtnGVGnM58D+UYWUeH0OtlOIWheLOhMwNojqYyAptaSW1k/CKRB6BAvojwn9PsQqkGZYuL/CKXgwbftkVK75ZIJ/XQP8syKhjRTK+FE+sHdQM/r1GW+xDFx0nWI4Dwza5/MmDaz+ILV3uwE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
