travis:
  secure:
    BINSTAR_TOKEN: XD5E6SENJQzuyGE1zOVE0k2y5DYcaYclCahyQIPxUQeaTKTZOr1ucuxVTe8XApHtfRuL/UWl+u3Jy3dCcWWXP/QxMgPGevppaWMKxdE8OpMRoaCnohLDz4l1sRK/W4HkBHIiQwfxGTO6vSrxRVf0BhSbLsrVGr2joKZjKf7HFXvR5iX+q3cNHtS9pw1yOdPzBAJ2mMzF+h0fpPT1sXhTYZL3J1XDqb4sMCKaw4LuUY91HgzUt560Q1NBeg8jbTJaoxEtXI7Naep1kJDFBfCW5rqCM4fjK10mfxOR4w0m27o7DQ5QAoJpUFz0i4jhfnQWOKr1nsm42PbH5VRjzl7ki8QwU1OC3EzTu//IMjJr01NYxoiYCrzD+KtntkxMBum4k9M5xlurnBCNWjGwcs6l7SOQmq2uOabSQSin+R9SetmuuU3t2lB9V+6x59MApGEvmxPO/eTtPVMEtKeU3Yazk7GCZBk1wle02CfwjyDoGXj7o/yuCH1r9hLC1XQuZwPH8T54nANTyYNosVk/NEYIuEjKY0WpN2mFuTVCnKitbUwSGnoPuFKWOR/VkyU71k38z/I4JROO+HP9g2zu+8XJmTwsEv0hxwwfo9Jqj4fIaHZlg8q8eDYP+QsexqVTTYBPdzbFImQ9octKysuYuazdNLp2pekapkKQeotpz5h5ivc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
