travis:
  secure:
    BINSTAR_TOKEN: yP7OWhNRaip05Se4HZQWdiOjyTT35zZyczutTvkZZ4Q/5XBNPq4PR+BwCPy2VtTwvS6B1ykyoFb0hOLBS/AOG6k9x4SAuLvxgFTWDWi28A5+vV6EdJf3ERbqampeVT2lfZhXSfTt+Rtmz4WAfGDMUZOHz3Cz2WTv+NTlgxbwXQ4JuyLxmBvI0tPiYX0RDAeJ7GXQQdNFG9mCVe1jWD9fcGrVmbbBsBhMtdc+bzfNclMQ/6U54hGyMkiIYKsA/5H/CZRvnTtgV5/C6uVNs5aPT7rgtOqm3C6lE4Lh8rEGqABx76XrzaOTBBrXxtemZiO738QA4XVTNJ6r2EDp6ArYups4IYzpRhb1bLZdOQEU6B+BEmhi5q2kqg3+8GxeZ/gQmmlKiNp4MT1qaf6iHDXjyJPtOZjHTJVJ5MM+M5LTOEpTkw5W2lvdP+2jJt3HCHWFY5BTyP7ylLuhtXZ0olp4r0E1aUpicJKBYFgPf9kR4pWbJp2ts42M4X9IYHvXftAK8RQ+mpJFAexhs1X7SOD76pBYT9yVD+5e13liUEXg9EteKWVV9b1mvJRu7TsTcZ4uhArgfgVWe8dzbMf9UG5+QdrYwd+SXlKo2yFw1wjiaoTZRgFUaxl9h3M0288uA8TzDd045I1PaD+0++LFkaNvM3jgKjh+08FFPeyYw5rPH/c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
