travis:
  secure:
    BINSTAR_TOKEN: VAIWKv84r8AGR8Vv0nSGOrip/HUCcp+n2oZjWiSmtWAMJ9RkIeItZoeNMf8im/nvIg+V8PA4nHVU41quXBZ/UFN2IsoKeTsvCHyMeJYtng0cqcI+67WPEOkk1mqZjwSNEjGsNwIRAIfiFdU2CGFMUhQ1p4UDkuYZ2QoDCt/YJN4DwEbj1Bf5bX94IprLCHP1Kk4dnM/PZULZpK1kJnQvLquGR14EoyDAe1xfi75nnQ/7y3zqEUQOhmSU1cUk/exrjMo4oPDmgK+O8sKkUnk0Q+KP09Ar/mIgJVdTpEmXeJjel3C5i3qfJRIUddpSLfoz15IHSgP2JYSRDCwykPY/2I0dLefAgJCNzekVPKsiDTe0vVyRTODfahFWRneE2ODZ5yxbvLDME/2cFzdUcsu70s5xgKKEWXNbX6rhXXy3WtOa7G7paVhdePftEBBqmMpB5mOu99dMtEgv/wdqrxQS+4rSXEuqPgDfkQWnZIcQMo4T1KAdvGiBoV53SXuJri3Re6lvwq9lGtbKG2NUHxPi8NkyirH7iox+FtDPiRQlYOLHjAOvJKzaIZKfojgsBX3CCnp7ZIYbRRJfanNdd1xZMC9h//KZE8aVELsirDN1ojahTLkQYuc07BkMs8Trfad2UIe4JLpxPla7kPGyOeCsx8Amaw1flViKYdfWHZeeLKU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
