travis:
  secure:
    BINSTAR_TOKEN: ABo1/0huunRwoXO2gm4RIdYk0DL7RJpY/aa141cfsKXL+sWqK6ywA4Tum+jE/nRB3FwemZxesz/8AahLbV3juYjeWMIXAfxWgpR/VdJH/5tFyUCoZHmQqMlbpDMBqFcDBmrtcmFeSmKI/zzfETnlpbCzl21eYOatR1Bn8mP0WARekqySysUvc0HSC1Qo9s0Z1AmQQYr7m2mBNh2xYZdvGBM3z+1DFsMqJvyDyEsZ8RFLnFCZCaF2gfqv/p7xS48GJfNbXD5kLlz7FFGcgFT+Rh2Cn9mAl6q5P3UlK7+n5dx9LoEW1CxeeZHbYuoK+bZs4oxeV/VYnXQbZukUwdDy80P7oNv2f6hDCQjEzHpmXVuHm7eQl1x8ITS1sytHN9PKbRc3hYJZeY4nY+p10C9vZne6RvTDrIeKcJpixJwVf3LhJq+ZgTBKd9OWEwiJ3jAYZJvpEEkGUZB5VsbFmY8LuWtAWdn50mCsL3JLV38KL2lZW0+HJgBZrZXL6pETeOmUKy7fz9LpK8X11rm20sy/qWFn4PpftlIYIuwhHcV04SlhDA6NtCagRmxbXlBg+FcU6e7J631Nz4JPoN7LnxSvtwRfxynXfkQ/eIYxuUdAIWLF+Oy281Gj1bN0tF+3y23r2FzDTvzpY8PdZzHjALetKtowS8jBWwX52+8Pv/kmafI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
