travis:
  secure:
    BINSTAR_TOKEN: 3Ts+s7Q0/q7/5tmGM8jDFQ3PCVgRI2TX3sSUoqwYV2RxXkrnCG2ouw2hSo+xr75bMFLtaINXAlXSbzffKAGUrQAQdcyptG5NzCdE9GewnM2NBYKscX8iPb7ivWp0XarWqkJgjx61DCEUjwwbp9htTFc7bSkhTYUsd0SsP02lQp7xK1rmxs3Upsi9ZM4U6JZV82Bs63zPHS4VD7xlnMVfo7RPBaG1S1/ME+iH8E4dQxTWjEXa8UB1mLM575znf8ck/WxoUIHEYA0NhDC+zJvRsWhZd8Ng3aLRZOTwnwGsOTkiOVsGBmCFETackCjwTAdXhIglZnHg877GhBRj5QRrmJp82M8YWO0t++RLZR+EgQ6PNYiI9IZj5nSPAKMMi6BafrafsBqBVQYcHxuUqiKxrmn2Jd0OkAVFtvXcFq5BBRuGgfmJKVFCgiIm1qFtds4cKYmKnuKOXyReUFHLb/ajLYIvyt6JsoedsFCdbWpuSActDmO9BIbauhMfttjRFt2zrKfZ7tJIvFwowCgQ1oNQDwC8DlOkEM2gRRUJxVKKXcDj1Ie8oP10uNSYJwMB5ojAJmlmnMC93hBU+fLNA41E+b6z6MaqKtfwDHaTkP8Q5tEbERf5jzoRSyRmM8412Xt3jTR+wQAUzvG+hNt4K0Y/z/et8l6aWfng0MJi6YtJxlM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
