travis:
  secure:
    BINSTAR_TOKEN: rnANwVBkX3D/GoOF9wl7K/lIj8tnPJlF3vOvl+gBYHjVQNx88AwxVg9yFmglXtiQhUaKufkZogX8/50ybimbYhyqgNOuA3xtC7sGu9lrrrHUyfJMQelGX+0V95Go9DeLDNoAd5YDtYjboEgV6l8FgSQkxIWcTP1w59GLDky8KTq8gXiQSmba/CCDu+Qkrxa/gh4KxbkPq3JBm09ifZ04+2yQOe5EdYREGlBSOa1mccBkjQIg/Mu6faE4cJ53/BzvLmXyM8n74muwjuWGAqUiU7QmVlWUTxgcl+F5nRNRYVhZa1mykmTq4cyAzVhwv0lAtTNmG6iNsuEeg2mV3QYBJ6cwLhUIasMypTGnBS1wBO0XuGZb75TQdvaO30rhmiiTvpMyGv8q3iAGX5pwPFURzxwY5i16BYW+ZV8H2+pmRYUBBwfcJvJhq33RAj3AZeu7jU3tCBGUlZGnGt8UHyPrCUEIU613k97vtJphJLJGDnXyREW+IV8UQIrBwMaWLH2nxReVgchgTxi313uF+caCwN4OPO0LLgLGkz4PrVS2YtmBuaREK3V7EGy2Tuyf1wBmy+prh3uVSMThQG6Dubsn5+Q/Yi20aAshk1aAsj7ZyYvNamzwZcg3C9dXomDGMh2n4buu2PP1JIYqgohao/5aURx5xa+whipR5QX/XRXje3o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
