travis:
  secure:
    BINSTAR_TOKEN: ohsQvOdSsCogvfdR6seuz6ujbhTogrVpUw5NQuacNHrHk2DvsfnnFSCbUaAfjAbPt3rxTfxIcqeP9uJNjKXc8dQPaDN/EbVjsxLMpEB2JtILN1aAQLqosW7qP736NYLwqiiMkntvddolRh/nLZMWiVQZ94IDqDNqKTOEtjSiKtUqVHArcFE607fVkB6zQFEZt9FAhbkUDmJCCt//hcNXMYHLONQq5xLeyGrV7LAbHNeqUk5Om6rQhRnwf4c/Id7mht69d7TQVtmWRoYsMGnKwjUxk0sqfhAJRRFZaDPZ68eHpYjSAbKRkdiNTbb2jFIVzEFbXAVGqmh6H5Sy7eAb+DvEguuY3nwipQR5z56Fitin/iAY+lcuVwcssooCGpDXAfQWM13ZdYJP6p4Nu0O28tKZpCsauRb8pcLFEQQzMBkO6/d1xuYyi6jLZxNXdiPsp0XKxoxHOk/jAEZ3nOgnsU3lS3Zur6eUyCPl175hI4Z5QzT+6o7xOoyAN/agExmcpRIuNAvySN5sd4gDM7+ME9AH1bLzSXCUj12FRHHpVJbeU0JVSZVNZzz+ad9ju2i/FYtIencpIKlc7Jck6ktiSnHaQkmH4IbC6DV1F2+Zso1CxXasCzdY+akEG1NcZBFyXm6UJAkwVBPKzVUiTPnDUPP3E6APPwVRfVoYfrntdMs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
