travis:
  secure:
    BINSTAR_TOKEN: U988nWpqIMEtPh20cmLouxMH724vPgeqTCwKSmBUJgA2opC8p3RT+YAlbFQQmW8gQYbfM615mF8+b8FZ2sr131Wnmp1jJFMU+KBVpptBDJx+fQ501motaxPi8kEOJUA01PqAdnRJyZd/AATZwfC4IWw0hot+CSWxHT1sKnvxZGwNA0zotld8X65zMp+FO7CEDf4aDNG2JQFRWVCTJN3moNMYz5uqb6Gvzx6dNuHb3zbc2hf7IO+EO6/YJjdwstuQRGu5uzn9I3w8sPBqZwE4rChxN/SOAoteAk56p7FrOcYFwiZrS+zTNnJNVu2dn+BDXePGyUsBEcSejdk7E93zbidLNwloLrHhy95qhubVnlVx0bnstGXLVypZ5jIAkGkafzdLztG5pRaBlbYQO9ILuQpPkURp2S1GbkhL3WZY76bPf9BYBHhHgnC43EaUoGLhs5i/ykGyTDWxT/wc4I8it/gEPLlM48QI4+A+ATy/Vg7OB21KX/m1V3jBEpjuPhyEjmWuInTpaYn/UebE7nOPpfSyy9EhbftaOf7atctrCrGkofSRMQpOSU4g6XNkdiY+O3pCuYERX9Vb/coWsiYstIiLLFFJyHKEbWa3XQoM1TrbnqxG4JpCZ4XnqosUF9DeuD4lqjNO3TzDU9OjE+goZl6gG8uqDBjeKmYQLWJ9qQ0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
